-- AlterTable
ALTER TABLE "FeeStructure" ADD COLUMN     "description" TEXT,
ADD COLUMN     "endDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "otherFee" DECIMAL(65,30) NOT NULL DEFAULT 0.00,
ADD COLUMN     "startDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "tuitionFee" SET DEFAULT 0.00;
